-- Migration: Recreate works table to match Google Sheet columns structure
-- This migration adjusts the works table to align with the Google Sheet data structure
-- Date: 2025-10-29

-- Create backup first (highly recommended before dropping table)
CREATE TABLE IF NOT EXISTS works_backup_20251029 AS
SELECT * FROM works;

-- Drop the existing works table and its indexes/triggers
DROP TABLE IF EXISTS works CASCADE;

-- Recreate the works table with columns matched to Google Sheet
CREATE TABLE public.works (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Core identification fields
  scheme_sr_no TEXT NOT NULL,
  scheme_name TEXT NULL,
  work_name TEXT NULL,

  -- Civil hierarchy (matches Google Sheet exactly)
  civil_zone TEXT NULL,
  civil_circle TEXT NULL,
  civil_division TEXT NULL,
  civil_sub_division TEXT NULL,

  -- Location and administrative details
  district_name TEXT NULL,
  je_name TEXT NULL,
  work_category TEXT NULL,
  site_name TEXT NULL,

  -- Legacy location fields (keeping for backward compatibility)
  zone_name TEXT NULL,
  circle_name TEXT NULL,
  division_name TEXT NULL,
  sub_division_name TEXT NULL,

  -- Financial details
  sanction_amount_lacs NUMERIC(12,2) NULL,
  amount_as_per_bp_lacs NUMERIC(12,2) NULL, -- Legacy field
  tender_no TEXT NULL,
  boq_amount NUMERIC(12,2) NULL,
  agreement_amount NUMERIC(12,2) NULL,
  bill_no TEXT NULL,
  bill_amount_with_tax NUMERIC(12,2) NULL,

  -- Tender and procurement dates
  nit_date DATE NULL,
  part1_opening_date TEXT NULL, -- Keep as TEXT for flexible formats
  loi_no_and_date TEXT NULL,
  part2_opening_date DATE NULL,

  -- Agreement details
  rate_as_per_ag TEXT NULL,
  agreement_no_and_date TEXT NULL,

  -- Contractor/Firm information
  firm_name_and_contact TEXT NULL,
  firm_contact_no TEXT NULL,
  firm_email TEXT NULL,

  -- Timeline
  start_date DATE NULL,
  scheduled_completion_date DATE NULL,
  expected_completion_date DATE NULL,
  actual_completion_date DATE NULL,

  -- Progress and status
  weightage INTEGER NULL,
  progress_percentage INTEGER NULL DEFAULT 0,
  wbs_code TEXT NULL,

  -- Status fields
  mb_status TEXT NULL,
  teco_status TEXT NULL,
  fico_status TEXT NULL,

  -- Legacy status fields
  teco TEXT NULL,
  fico TEXT NULL,

  -- Distribution hierarchy (matches Google Sheet exactly)
  distribution_zone TEXT NULL,
  distribution_circle TEXT NULL,
  distribution_division TEXT NULL,
  distribution_sub_division TEXT NULL,

  -- Additional fields
  remark TEXT NULL,
  site TEXT NULL, -- Additional site field
  email_id TEXT NULL, -- Legacy field

  -- Blocking functionality
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  blocker_remark TEXT NULL,

  -- Audit fields
  created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),

  -- New fields (if needed for future updates)
  edc TEXT NULL,
  edd TEXT NULL,
  edsd TEXT NULL,
  scheme_name_new TEXT NULL,
  scheme_sr_no_new TEXT NULL,
  je_name_new TEXT NULL,
  work_category_new TEXT NULL,
  work_name_new TEXT NULL,
  amount_as_per_bp_lacs_new NUMERIC(12,2) NULL,
  boq_amount_new NUMERIC(12,2) NULL,
  agreement_amount_new NUMERIC(12,2) NULL,
  rate_as_per_ag_new TEXT NULL,
  firm_name_and_contact_new TEXT NULL,
  firm_contact_no_new TEXT NULL,
  start_date_new DATE NULL,
  scheduled_completion_date_new DATE NULL,
  weightage_new NUMERIC NULL,
  progress_percentage_new NUMERIC NULL,
  remark_new TEXT NULL,
  wbs_code_new TEXT NULL,
  mb_status_new TEXT NULL,
  teco_status_new TEXT NULL,
  fico_status_new TEXT NULL,

  CONSTRAINT works_scheme_sr_no_unique UNIQUE (scheme_sr_no)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS works_je_name_idx ON works (je_name);
CREATE INDEX IF NOT EXISTS works_district_name_idx ON works (district_name);
CREATE INDEX IF NOT EXISTS works_work_category_idx ON works (work_category);
CREATE INDEX IF NOT EXISTS works_civil_zone_idx ON works (civil_zone);
CREATE INDEX IF NOT EXISTS works_civil_circle_idx ON works (civil_circle);
CREATE INDEX IF NOT EXISTS works_civil_division_idx ON works (civil_division);
CREATE INDEX IF NOT EXISTS works_civil_sub_division_idx ON works (civil_sub_division);
CREATE INDEX IF NOT EXISTS works_distribution_zone_idx ON works (distribution_zone);
CREATE INDEX IF NOT EXISTS works_distribution_circle_idx ON works (distribution_circle);
CREATE INDEX IF NOT EXISTS works_distribution_division_idx ON works (distribution_division);
CREATE INDEX IF NOT EXISTS works_distribution_sub_division_idx ON works (distribution_sub_division);
CREATE INDEX IF NOT EXISTS works_scheme_sr_no_idx ON works (scheme_sr_no);
CREATE INDEX IF NOT EXISTS works_is_blocked_idx ON works (is_blocked);

-- Create the updated_at trigger function if it doesn't exist
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER on_works_update
    BEFORE UPDATE ON works
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

-- Enable RLS (Row Level Security) if needed
ALTER TABLE works ENABLE ROW LEVEL SECURITY;

-- Add RLS policies for the works table
-- Drop existing policies to ensure a clean slate
DROP POLICY IF EXISTS "Allow all users to read works" ON public.works;
DROP POLICY IF EXISTS "Allow superadmins to manage works" ON public.works;

-- 1. Create a policy to allow all authenticated users to read data
CREATE POLICY "Allow all users to read works"
ON public.works
FOR SELECT
USING (auth.role() = 'authenticated');

-- 2. Create a policy to allow superadmins to insert, update, and delete
CREATE POLICY "Allow superadmins to manage works"
ON public.works
FOR ALL
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'superadmin'
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'superadmin'
);

-- Note: After running this migration:
-- 1. Restore data from works_backup_20251029 if needed
-- 2. Update any application code that references old column names
-- 3. Test the Google Sheet sync functionality
-- 4. The column structure now directly matches the Google Sheet headers
